CarFuel.Web/Controllers/TodoController.cs
using CarFuel.Models;
using CarFuel.Services;
using System;
using System.Linq;
using System.Web.Mvc;

namespace CarFuel.Web.Controllers {

  [Authorize]
  public class TodoController : Controller {

    private readonly ITodoItemService todoService;

    public TodoController(ITodoItemService todoService) {
      this.todoService = todoService;
    }

    public ActionResult Index() {

      var items = from item in todoService.All()
                  orderby item.IsDone
                  select item;

      return View(items.ToList());
    }

    public ActionResult Create() {
      return View();
    }

    [HttpPost]
    public ActionResult Create(TodoItem item) {
      if (ModelState.IsValid) {

        try {   
          todoService.Add(item);
          todoService.SaveChanges();
        }
        catch (Exception ex) {
          TempData["error"] = ex.Message;
        }

        return RedirectToAction("Index");
      }
      return View(item);
    }

    [HttpPost]
    public ActionResult MarkAsComplete(int id) {
      todoService.MarkAsComplete(id);
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult CancelComplete(int id) {
      todoService.CancelComplete(id);
      return RedirectToAction("Index");
    }


  }
}

CarFuel.Web/Views/Todo/Create.cshtml
@model CarFuel.Models.TodoItem

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TodoItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div> 

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CarFuel.Web/Views/Todo/Index.cshtml
@model IEnumerable<CarFuel.Models.TodoItem>

@{
  ViewBag.Title = "Index";
}

<h2>Todo</h2>

@if (TempData["error"] != null) {
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    @TempData["error"]
  </div>
}


<p>
  @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
  <tr>
    <th>
      @Html.DisplayNameFor(model => model.Description)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.IsDone)
    </th>
    <th>
      @Html.DisplayNameFor(model => model.AddedDate)
    </th>
    <th></th>
  </tr>

  @foreach (var item in Model) {
    <tr>
      <td>
        @Html.DisplayFor(modelItem => item.Description)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.IsDone)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.AddedDate)
      </td>
      <td>
        @if (!item.IsDone) {
          using (Html.BeginForm("MarkAsComplete", "Todo", new { id = item.Id })) {
          <button type="submit" class="btn btn-success btn-xs">Done</button>
          }
        } else {
          using (Html.BeginForm("CancelComplete", "Todo", new { id = item.Id })) {
          <button type="submit" class="btn btn-danger btn-xs">Cancel</button>
          }
        }

        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
      </td>
    </tr>
  }

</table>